[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL          = "https://vumjslsogdnexehutibj.supabase.co"
  VITE_SUPABASE_ANON_KEY     = "sb_publishable_xGyIdQwX9eZqGDkCz893Pg_algfSfAm"
  VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_51JndOpCUoqNzIKpeg4UUoInU28inBCR9qfqnFipwnY56cAtmhrSp85O3xTO4xBpNAw2bwooOv78y3Vc25pHpkWaI00mTqv3uwO"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
