[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL          = "https://vumjslsogdnexehutibj.supabase.co"
  VITE_SUPABASE_ANON_KEY     = "sb_publishable_xGyIdQwX9eZqGDkCz893Pg_algfSfAm"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
