-- Transparent product photos. The discusfood.com photos imported in
-- 20260705010000 were mostly shot on a WHITE background, which showed as a white
-- box around the product on the storefront's dark cards. Their background was
-- flood-filled to transparency (edge-connected near-white only, so white detail
-- inside the product is preserved) and re-uploaded as PNG. This points the
-- affected products at the transparent .png versions. Photos already shot on a
-- dark/transparent background were left unchanged. Keyed by slug -> idempotent.

UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/african-cichlid-colour.png', updated_at = now() WHERE slug = 'african-cichlids-color-soft-pearls';  -- 20079
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/african-cichlid-spirulina.png', updated_at = now() WHERE slug = 'african-cichlids-spirulina-soft-pearls';  -- 20078
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/algae-wafers.png', updated_at = now() WHERE slug = 'pleco-catfish-algae-wafers-50g';  -- 23001
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/algae-wafers.png', updated_at = now() WHERE slug = 'pleco-catfish-algae-wafers';  -- 23012
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/algae-wafers.png', updated_at = now() WHERE slug = 'plecs-catfish-algae-wafers';  -- 23112
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/amazon-tonic.png', updated_at = now() WHERE slug = 'amazon-tonic';  -- 25305
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/amazon-tonic.png', updated_at = now() WHERE slug = 'amazon-tonic-5000ml';  -- 25350
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/american-cichlid-colour.png', updated_at = now() WHERE slug = 'american-cichlids-color-soft-pearls';  -- 20077
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/american-cichlid-spirulina.png', updated_at = now() WHERE slug = 'american-cichlids-spirulina-soft-pearls';  -- 20076
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/angelfish-supergrowth.png', updated_at = now() WHERE slug = 'angelfish-special-soft-granulate';  -- 20082
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/angelfish-supergrowth.png', updated_at = now() WHERE slug = 'angelfish-special-soft-granulate-230g';  -- 20822
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/angelfish-supergrowth.png', updated_at = now() WHERE slug = 'angelfish-special-soft-granulate-550g';  -- 20823
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/anti-tox.png', updated_at = now() WHERE slug = 'anti-tox';  -- 25405
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/artemia-decapsulated-eggs.png', updated_at = now() WHERE slug = 'decapsulated-artemia-eggs';  -- 20061
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/artemia-flat-65g.png', updated_at = now() WHERE slug = 'artemia-50-flat-granulate';  -- 20051
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/artemia-micro-45g.png', updated_at = now() WHERE slug = 'artemia-50-micro-granulate-soft';  -- 20052
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/artemia-premium-eggs.png', updated_at = now() WHERE slug = 'artemia-50-cysts';  -- 20062
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/artemia-soft-150g.png', updated_at = now() WHERE slug = 'artemia-50-soft-granulate';  -- 20050
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/beef-heart-soft.png', updated_at = now() WHERE slug = 'beef-heart-soft-granulate';  -- 20071
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/beef-heart-soft.png', updated_at = now() WHERE slug = 'beef-heart-soft-granulate-230g';  -- 20712
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/beef-heart-soft.png', updated_at = now() WHERE slug = 'beef-heart-soft-granules';  -- 20711
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/beef-heart-soft.png', updated_at = now() WHERE slug = 'beef-heart-soft-granulate-2800g';  -- 20715
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/beefheart-paste-color.png', updated_at = now() WHERE slug = 'beef-heart-paste-color';  -- 20288
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/best-heart-flake-blue-dream.png', updated_at = now() WHERE slug = 'best-heart-flakes-blue-dream';  -- 20043
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/best-heart-flake-golden-dream.png', updated_at = now() WHERE slug = 'best-heart-flakes-golden-dream';  -- 20044
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/best-heart-flake-pro-breed.png', updated_at = now() WHERE slug = 'best-heart-flakes-pro-breed';  -- 20042
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/best-heart-flake-red-dream.png', updated_at = now() WHERE slug = 'best-heart-flakes-red-dream';  -- 20045
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/best-heart-flake-super-growth.png', updated_at = now() WHERE slug = 'super-growth';  -- 20041
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/betta-special.png', updated_at = now() WHERE slug = 'betta-special-all-colors-soft';  -- 20080
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/breeder-starter-i.png', updated_at = now() WHERE slug = 'breeder-starter-food-1';  -- 20083
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/breeder-starter-ii.png', updated_at = now() WHERE slug = 'breeder-starter-food-2';  -- 20084
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/brine-shrimp-artemia-paste.png', updated_at = now() WHERE slug = 'brine-shrimp-artemia-paste';  -- 20289
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/buffet-di-insect.png', updated_at = now() WHERE slug = 'buffet-di-insect';  -- 20059
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/carni-wafers.png', updated_at = now() WHERE slug = 'pleco-catfish-carni-wafers-50g';  -- 23002
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/carni-wafers.png', updated_at = now() WHERE slug = 'pleco-catfish-carni-wafers';  -- 23022
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/carni-wafers.png', updated_at = now() WHERE slug = 'plecs-catfish-carni-wafers';  -- 23122
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/catappa-royal.png', updated_at = now() WHERE slug = 'royal-catappa';  -- 25505
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/catappa-royal.png', updated_at = now() WHERE slug = 'royal-catappa-5000ml';  -- 25550
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/cichlids-xl-1.png', updated_at = now() WHERE slug = 'cichlids-xl-granulate-1';  -- 20030
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/cichlids-xl-2.png', updated_at = now() WHERE slug = 'cichlids-xl-granulate-2';  -- 20031
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/day-by-day.png', updated_at = now() WHERE slug = 'for-discus-daily-granulate';  -- 20064
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/day-by-day.png', updated_at = now() WHERE slug = 'for-discus-daily-granulate-230g';  -- 20642
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/day-by-day.png', updated_at = now() WHERE slug = 'for-discus-daily-granulate-2800g';  -- 20645
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/discus-minerals.png', updated_at = now() WHERE slug = 'discus-minerals';  -- 33020
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/discus-minerals.png', updated_at = now() WHERE slug = 'discus-minerals-1000g';  -- 33050
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/freshwater-crab-micro.png', updated_at = now() WHERE slug = 'freshwater-crab-micro-granulate-soft';  -- 22062
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/freshwater-crab-soft.png', updated_at = now() WHERE slug = 'freshwater-crab-soft-granulate';  -- 22060
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/freshwater-crab-xl.png', updated_at = now() WHERE slug = 'freshwater-crab-xl-soft-granulate';  -- 22063
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/frutti-di-mare.png', updated_at = now() WHERE slug = 'frutti-di-mare';  -- 20060
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/grand-champion.png', updated_at = now() WHERE slug = 'grand-champion-granulate';  -- 20055
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/grand-champion.png', updated_at = now() WHERE slug = 'grand-champion-granulate-230g';  -- 20552
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/guppy-super-color.png', updated_at = now() WHERE slug = 'guppy-super-color-soft';  -- 27475
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/guppy-super-special.png', updated_at = now() WHERE slug = 'guppy-super-special-soft';  -- 20073
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/natural-humin.png', updated_at = now() WHERE slug = 'natural-humin';  -- 25105
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/natural-humin.png', updated_at = now() WHERE slug = 'natural-humin-5000ml';  -- 25150
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/pleco-special.png', updated_at = now() WHERE slug = 'wels-special-soft-80g';  -- 20001
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/pleco-special.png', updated_at = now() WHERE slug = 'wels-special-soft';  -- 20012
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/pleco-special.png', updated_at = now() WHERE slug = 'catfish-special-soft-granulate';  -- 20112
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/shrimp-paste.png', updated_at = now() WHERE slug = 'shrimp-paste';  -- 20293
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/turkey-heart-soft.png', updated_at = now() WHERE slug = 'turkey-heart-soft-granulate';  -- 20070
UPDATE public.products SET image_url = 'https://vumjslsogdnexehutibj.supabase.co/storage/v1/object/public/product-images/products/discusfood/turkey-heart-soft.png', updated_at = now() WHERE slug = 'turkey-heart-soft-granulate-230g';  -- 20702
